In [3]:
# packages
import numpy as np

## Simple numpy array creation

In [5]:
a = np.array([14,25,36,144,65, 45])
a

array([ 14,  25,  36, 144,  65,  45])

In [6]:
#using zero function
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [7]:
#using ones function
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [8]:
# using empty function
a = np.empty(5)
a

array([1., 1., 1., 1., 1.])

In [13]:
# using range function
a = np.arange(5)
print(a)

a = np.arange(1,8,2)
a

array([1, 3, 5, 7])

In [16]:
# using linspace function
a = np.linspace(1,9,num=100)
a

array([1.        , 1.08080808, 1.16161616, 1.24242424, 1.32323232,
       1.4040404 , 1.48484848, 1.56565657, 1.64646465, 1.72727273,
       1.80808081, 1.88888889, 1.96969697, 2.05050505, 2.13131313,
       2.21212121, 2.29292929, 2.37373737, 2.45454545, 2.53535354,
       2.61616162, 2.6969697 , 2.77777778, 2.85858586, 2.93939394,
       3.02020202, 3.1010101 , 3.18181818, 3.26262626, 3.34343434,
       3.42424242, 3.50505051, 3.58585859, 3.66666667, 3.74747475,
       3.82828283, 3.90909091, 3.98989899, 4.07070707, 4.15151515,
       4.23232323, 4.31313131, 4.39393939, 4.47474747, 4.55555556,
       4.63636364, 4.71717172, 4.7979798 , 4.87878788, 4.95959596,
       5.04040404, 5.12121212, 5.2020202 , 5.28282828, 5.36363636,
       5.44444444, 5.52525253, 5.60606061, 5.68686869, 5.76767677,
       5.84848485, 5.92929293, 6.01010101, 6.09090909, 6.17171717,
       6.25252525, 6.33333333, 6.41414141, 6.49494949, 6.57575758,
       6.65656566, 6.73737374, 6.81818182, 6.8989899 , 6.97979